### ISSUE TITLE
v0.10.1-alpha endgame

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1006]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @digadeesh  |
| QA      | @y-f-u  |
| Docs    | @phillipleblanc  |
| Comms   | @lukekim |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Mar 25 |
| Release      | Mon, Apr 1 |
| Announcement | Mon, Apr 1 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @digadeesh 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @y-f-u 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @phillipleblanc 
- [x] Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!) @sgrebnov 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @ewgenius 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @Jeadie 
- [x] ~Merge Registry PRs~
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @phillipleblanc 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls) @phillipleblanc 
- [x] Update release notes @digadeesh 
- [x] Update acknowledgements by triggering [Generate Acknowledgements] (https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @Jeadie 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @digadeesh 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @digadeesh 
- [x] Release any docs updates by creating a `v[semver]` tag. @phillipleblanc 
- [x] If there were any changes to the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart), update the Helm chart version and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @phillipleblanc 
- [x] Final test pass on released binaries - @y-f-u 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @sgrebnov 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @digadeesh 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @y-f-u 
- [x] ~Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)~ @digadeesh 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

## PR reference

- PR 1.
- PR 2.
- etc.
