### ISSUE TITLE
v0.10.2-alpha endgame

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1043]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @Jeadie  |
| QA      | @sgrebnov  |
| Docs    | @y-f-u  |
| Comms   | Kari Fabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Monday 8th April |
| Release      | Monday 8th April  |
| Announcement | Monday 8th April  |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @phillipleblanc 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @y-f-u 
- [x] Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!) @ewgenius 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @sgrebnov 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls)
- [x] Merge Registry PRs
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls)
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls)
- [x] Update release notes
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @Jeadie 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @Jeadie 
- [x] Release the new version by creating a `pre-release` [GitHub Release] (https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @Jeadie 
- [x] Release any docs updates by creating a `v[semver]` tag. @y-f-u 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @Jeadie 
- [x] Final test pass on released binaries
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)

## Announcement Checklist
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @Jeadie 

###
@lukekim & Kari
- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)

**Comment by Jeadie** [comment]
Feature PRs up to https://github.com/spiceai/spiceai/commit/7dfb5c4249dd532924c39c83dc973628b18d7bbf

**Comment by Jeadie** [comment]
Outstanding docs PR:
- https://github.com/spiceai/docs/pull/186

No outstanding samples/quickstarts PRs

**Comment by Jeadie** [comment]
E2E Test CI passing on trunk: https://github.com/spiceai/spiceai/actions/runs/8605008937

**Comment by Jeadie** [comment]
Updating Helm chart and image tags:
- https://github.com/spiceai/spiceai/pull/1044
- https://github.com/spiceai/spiceai/pull/1045

**Comment by Jeadie** [comment]
No changes in acknowledgements: https://github.com/spiceai/spiceai/actions/runs/8607544257

**Comment by Jeadie** [comment]
Waiting on https://github.com/spiceai/spiceai/actions/runs/8608161244 to release helm updates.

**Comment by Jeadie** [comment]
Running E2E test on new release binaries: https://github.com/spiceai/spiceai/actions/runs/8609054665

**Comment by lukekim** [comment]
Reddit: https://www.reddit.com/r/spiceai/comments/1bzgvig/spice_v0102alpha_is_now_available/

**Comment by Jeadie** [comment]
Charts deployed: https://github.com/spiceai/helm-charts/actions/runs/8609932281

**Comment by digadeesh** [comment]
Closing this out.
