### ISSUE TITLE
v0.11.0-alpha endgame

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1103]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @sgrebnov  |
| QA      | @sgrebnov |
| Docs    | @ewgenius  |
| Comms   | Kari Fabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Mar 15 |
| Release      | Mon, Mar 15  |
| Announcement | Mon, Mar 15  |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @sgrebnov 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @Sevenannn 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @ewgenius 
- [x] ~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~ . To be done after release as Spice is installed using install.sh (currently released version is used)
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @Jeadie 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @Jeadie + @ewgenius 
- [x] Merge Registry PRs @sgrebnov 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @sgrebnov 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls) @sgrebnov 
- [x] Update release notes @sgrebnov 
- [x] Update acknowledgements by triggering [Generate Acknowledgements] @sgrebnov (https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @sgrebnov 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha`
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @sgrebnov 
- [x] Release any docs updates by creating a `v[semver]` tag. @sgrebnov 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @Jeadie 
- [x] Final test pass on released binaries @ewgenius 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @sgrebnov 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @sgrebnov 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @y-f-u 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @sgrebnov 

## Announcement Checklist (Kari)

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

**Comment by sgrebnov** [comment]
Spice v0.11.0-alpha has been released 🎉
https://github.com/spiceai/spiceai/releases/tag/v0.11.0-alpha
