### ISSUE TITLE
v0.11.1-alpha endgame

### ISSUE THREAD

**Issue by y-f-u** [spiceai/spiceai#1153]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @y-f-u  |
| QA      | @sgrebnov  |
| Docs    | @digadeesh  |
| Comms   | @karifabri  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Sun, 14 Apr |
| Release      | Mon, 22 Apr |
| Announcement | Tue, 23 Apr |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @sgrebnov 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @digadeesh 
- [ ] ~~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~~ @y-f-u 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @sgrebnov 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @y-f-u 
- [x] Merge Registry PRs
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls)
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls) @y-f-u 
- [x] Update release notes @lukekim  
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @y-f-u 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md] (https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @y-f-u 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @y-f-u 
- [x] QA DRI sign-off @sgrebnov 
- [x] Docs DRI sign-off @digadeesh 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @y-f-u 
- [x] Release the new version by creating a `pre-release` [GitHub Release] (https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @y-f-u 
- [x] Release any docs updates by creating a `v[semver]` tag. @digadeesh 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @Jeadie 
- [x] Final test pass on released binaries @y-f-u 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @y-f-u 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @y-f-u 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @y-f-u 
- [ ] ~~Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)~~ @y-f-u

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri 
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri 
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri 
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri 
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri 

## PR reference

- PR 1.
- PR 2.
- etc.
