### ISSUE TITLE
v0.12.0-alpha endgame

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#1172]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @ewgenius |
| QA      | @sgrebnov  |
| Docs    | @Jeadie  |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, 22 Apr |
| Release      | Mon, 29 Apr |
| Announcement | Tue, 30 Apr |

## Planning Checklist

- [x] Review the specific [v0.12-alpha GitHub Milestone](https://github.com/spiceai/spiceai/milestone/24)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @ewgenius 
- [x] Publish spiceai pods (`spiceai/fed-demo`, `spiceai/quickstart`) with updated `refresh_check_interval` @ewgenius 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @digadeesh 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @Jeadie
- [x] ~~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~~ @y-f-u 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @sgrebnov 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @Jeadie
- [x] Merge Registry PRs @ewgenius 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @ewgenius 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @ewgenius 
- [x] Update release notes @ewgenius - https://github.com/spiceai/spiceai/pull/1216
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @ewgenius 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @ewgenius 
- [x] QA DRI sign-off @sgrebnov
- [x] Docs DRI sign-off @Jeadie
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha`
- [x] Update release notes for SDKs @lukekim 
- [x] Publish spice sdk releases @ewgenius 
  - [x] spice.js @ewgenius 
  - [x] spicepy @ewgenius 
  - [x] spice-rs @ewgenius 
  - [x] gospice @ewgenius 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @ewgenius 
- [x] Release any docs updates by creating a `v[semver]` tag. @Jeadie
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @y-f-u 
- [x] Final test pass on released binaries @ewgenius 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @ewgenius 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @ewgenius 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @ewgenius 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @ewgenius 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri

## PR reference

- [x] https://github.com/spiceai/spiceai/pull/1216
- [x] https://github.com/spiceai/samples/pull/77
- [x] https://github.com/spiceai/quickstarts/pull/93
- [x] https://github.com/spiceai/docs/pull/214
