### ISSUE TITLE
v0.12.1-alpha endgame

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#1304]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @phillipleblanc |
| QA      | @y-f-u |
| Docs    | @digadeesh |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Apr 29 |
| Release      | Mon, May 6 |
| Announcement | Tue, May 7 |

## Planning Checklist

- [x] Review the specific [v0.12.1-alpha Milestone](https://github.com/spiceai/spiceai/milestone/20)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @phillipleblanc 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @ewgenius 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @digadeesh 
- [x] ~~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~~ @y-f-u 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @y-f-u 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @digadeesh 
- [x] Merge Registry PRs @phillipleblanc 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @y-f-u 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @y-f-u 
- [x] Update release notes @phillipleblanc 
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @phillipleblanc 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @phillipleblanc 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @y-f-u 
- [x] QA DRI sign-off @y-f-u 
- [x] Docs DRI sign-off @digadeesh 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @phillipleblanc 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @phillipleblanc 
- [x] Release any docs updates by creating a `v[semver]` tag. @digadeesh 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @digadeesh 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @ewgenius 
- [x] Final test pass on released binaries @phillipleblanc 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @phillipleblanc 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @phillipleblanc 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @phillipleblanc 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @phillipleblanc 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri 
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri 
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri 
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri 
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri 

## PR reference

- https://github.com/spiceai/spiceai/pull/1323
- https://github.com/spiceai/spiceai/pull/1315
- https://github.com/spiceai/spiceai/pull/1288

**Comment by phillipleblanc** [comment]
Release is done!
