### ISSUE TITLE
v0.12.2-alpha endgame

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1363]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @sgrebnov |
| QA      | @Jeadie |
| Docs    | @digadeesh |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, May 13 |
| Release      | Mon, May 13 |
| Announcement | Mon, May 13 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @sgrebnov
- [x] Full test pass and update if necessary over README.md @digadeesh 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @sgrebnov 
- [x] ~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @Jeadie 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @sgrebnov
- [x] Merge Registry PRs @sgrebnov
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @sgrebnov 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @sgrebnov 
- [x] Update release notes @sgrebnov + @lukekim
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @sgrebnov 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @Jeadie
- [x] QA DRI sign-off @Jeadie
- [x] Docs DRI sign-off @digadeesh
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @sgrebnov 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @sgrebnov 
- [x] Release any docs updates by creating a `v[semver]` tag. @sgrebnov 
- [x] Trigger algolia search crawler [workflow] (https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @sgrebnov 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @sgrebnov 
- [x] Final test pass on released binaries @sgrebnov 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @sgrebnov 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @sgrebnov 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @sgrebnov 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @sgrebnov 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri

## PR reference

- PR 1.
- PR 2.
- etc.

**Comment by Jeadie** [comment]
Quickstarts to test
- [x] https://github.com/spiceai/quickstarts/tree/trunk/postgres
- [ ] https://github.com/spiceai/quickstarts/tree/trunk/snowflake
- [x] https://github.com/spiceai/quickstarts/tree/trunk/refresh-data-window

**Comment by sgrebnov** [comment]
Release is fully completed.
