### ISSUE TITLE
v0.13.0-alpha endgame

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#1431]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @Jeadie  |
| QA      |  @ewgenius   |
| Docs    |  @sgrebnov  |
| Comms   | @karifabri  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | 20th May |
| Release      | 20th May |
| Announcement | 21st May |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @y-f-u 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @y-f-u 
- [ ] ~~Full test pass and update if necessary over existing and new Samples~~ (please get screenshots/videos!) @y-f-u 
- [ ] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @y-f-u 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @sgrebnov 
- [x] Merge Registry PRs
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @sgrebnov 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @sgrebnov 
- [x] Update release notes
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch
- [x] QA DRI sign-off
- [x] Docs DRI sign-off @sgrebnov 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha`
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha`
- [x] Release any docs updates by creating a `v[semver]` tag.
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs.
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow.
- [x] Final test pass on released binaries
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

## PR reference

- PR 1.
- PR 2.
- etc.

**Comment by Jeadie** [comment]
Quickstarts needed to test
- [x] https://github.com/spiceai/quickstarts/tree/trunk/ftp @ewgenius 
- [x] https://github.com/spiceai/quickstarts/tree/trunk/federation
- [x] https://github.com/spiceai/quickstarts/tree/trunk/s3 @y-f-u  
- [x] https://github.com/spiceai/quickstarts/tree/trunk/clickhouse @y-f-u

**Comment by Jeadie** [comment]
Docs needed:
- [x] FTP/SFTP
- [x] Updated [s3](https://docs.spiceai.org/data-connectors/s3) for CSV support

**Comment by Jeadie** [comment]
For this release, only bug fixes after commit https://github.com/spiceai/spiceai/commit/fa3279b7d9fcaa5e8baaa2425f69b556bb30e309

**Comment by Jeadie** [comment]
Acknowledgements: https://github.com/spiceai/spiceai/pull/1433

**Comment by Jeadie** [comment]
E2E Test CI: https://github.com/spiceai/spiceai/actions/runs/9165591346

**Comment by Jeadie** [comment]
Waiting on docker image build: https://github.com/spiceai/spiceai/actions/runs/9168341518
