### ISSUE TITLE
v0.13.2-alpha endgame

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#1567]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @ewgenius |
| QA      | @y-f-u |
| Docs    | @digadeesh |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, June 3 |
| Release      | Mon, June 3 |
| Announcement | Tue, June 4 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestone/22)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @ewgenius
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @y-f-u 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @digadeesh 
- [x] Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!) @y-f-u  
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @y-f-u 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @digadeesh 
- [x] Merge Registry PRs @ewgenius
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @ewgenius
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @ewgenius
- [x] Update release notes @ewgenius
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @ewgenius
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @ewgenius
- [x] QA DRI sign-off @y-f-u 
- [x] Docs DRI sign-off @digadeesh 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha`@ewgenius
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha`@ewgenius
- [x] Release any docs updates by creating a `v[semver]` tag. @ewgenius
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @ewgenius
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @ewgenius
- [x] Final test pass on released binaries @ewgenius
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @ewgenius
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @ewgenius
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @ewgenius
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @ewgenius

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri 
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri

## PR reference

- PR 1.
- PR 2.
- etc.

**Comment by ewgenius** [comment]
Test:

- [ ] MotherDuck @digadeesh 
- [x] GraphQL @ewgenius 
- [x] Caching changes @y-f-u
