### ISSUE TITLE
v0.14.0-alpha endgame

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#1704]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @sgrebnov  |
| QA      | @digadeesh  |
| Docs    | @ewgenius  |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Jun 10 |
| Release      | Mon, Jun 17 |
| Announcement | Tue, Jun 18 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] ~All features/bugfixes to be included in the release have been merged to the release branch (e.g. `release-v0.14.0-alpha`) following the [Branching Policy]~
  - [x] ~Verify all commits that should be included are in by viewing the GitHub compare view: i.e. https://github.com/spiceai/spiceai/compare/trunk...release-v0.13.2-alpha~
- [x] Full test pass and update if necessary over README.md @digadeesh 
- [x] Full test pass and update if necessary over Docs @ewgenius
- [x] Full test pass and update if necessary over existing and new Samples @y-f-u 
- [x] Full test pass and update if necessary over existing and new Quickstarts @digadeesh 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @ewgenius
- [x] Merge Registry PRs sgrebnov
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @sgrebnov
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @sgrebnov 
- [x] Update release notes @lukekim 
  - [x] Ensure any external contributors have been acknowledged.
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @sgrebnov 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @sgrebnov 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the release branch. @digadeesh 
- [x] QA DRI sign-off @digadeesh 
- [x] Docs DRI sign-off @ewgenius
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.14.0-alpha` @sgrebnov 
- [x] Release any docs updates by creating a `v[semver]` tag. @sgrebnov 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @sgrebnov
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @sgrebnov 
- [x] Final test pass on released binaries @sgrebnov 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @sgrebnov 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @sgrebnov 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @sgrebnov 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @sgrebnov 
- [x] ~Create a new branch `release-v[semver]` for the next release version from the current release branch. E.g. `release-v0.14.0-alpha`~

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

## PR reference

- PR 1.
- PR 2.
- etc.

[Branching Policy]: https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md

**Comment by sgrebnov** [comment]
Release is done
