### ISSUE TITLE
v0.17.0-beta endgame

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#2131]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @phillipleblanc |
| QA      | @peasee  |
| Docs    | @Jeadie  |
| Comms   | @karifabri  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Jul 22 |
| Release      | Mon, Jul 29 |
| Announcement | Tue, Jul 30 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk @phillipleblanc 
- [x] Full test pass and update if necessary over README.md @Jeadie 
- [x] Full test pass and update if necessary over Docs @Jeadie  
- [x] Full test pass and update if necessary over existing and new Samples 
  - [x] [TLS Sample](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @peasee
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @y-f-u  
  - [x] [Debezium CDC](https://github.com/spiceai/samples/tree/trunk/cdc-debezium) @ewgenius  
- [x] Full test pass and update if necessary over existing and new Quickstarts
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @peasee 
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @y-f-u 
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @sgrebnov  (tested; quick start is based on currently released helm chart, reviewed potential changes that can impact helm-none)
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @ewgenius 
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @y-f-u   
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @y-f-u 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @phillipleblanc 
- [x] Merge Registry PRs @phillipleblanc 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @phillipleblanc 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @phillipleblanc 
- [x] Update release notes @lukekim 
  - [x] Ensure any external contributors have been acknowledged. @phillipleblanc 
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius 
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md) @ewgenius 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @phillipleblanc 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the release branch. @peasee 
- [x] Ensure the [Benchmark Tests](https://github.com/spiceai/spiceai/actions/workflows/benchmarks.yml) are green on trunk. @peasee
- [x] QA DRI sign-off @peasee 
- [x] Docs DRI sign-off @Jeadie 
- [x] Create a new branch `release-v[semver]` for the release version from trunk. E.g. `release-v0.14.0-alpha` @phillipleblanc 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @phillipleblanc 
- [x] Release any docs updates by creating a `v[semver]` tag. @phillipleblanc 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @phillipleblanc  
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @y-f-u 
- [x] Final test pass on released binaries @peasee 
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml) @ewgenius 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @peasee 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @phillipleblanc 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @y-f-u 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @phillipleblanc 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

## PR reference

- PR 1.
- PR 2.
- etc.
