### ISSUE TITLE
v0.17.3-beta endgame

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#2455]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame |  @Jeadie  |
| QA      | @sgrebnov  |
| Docs    | @peasee  |
| Comms   | @karifabri  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | 27th August |
| Release      | 2nd September |
| Announcement |  3rd September |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk @Jeadie 
- [x] Full test pass and update if necessary over README.md @ewgenius 
- [x] Full test pass and update if necessary over Docs @Jeadie 
- [x] Full test pass and update if necessary over existing and new Samples
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @Jeadie 
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @phillipleblanc 
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @Sevenannn 
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @sgrebnov 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @peasee 
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @ewgenius 
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) @Jeadie 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @phillipleblanc 
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @Sevenannn 
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @sgrebnov 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @peasee 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @ewgenius 
- [x] Full test pass and update if necessary over existing and new Quickstarts
  - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @Jeadie 
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/README.md) @phillipleblanc 
  - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @Sevenannn 
  - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @sgrebnov 
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @peasee 
  - [x] [Supabase Data Connector Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @Jeadie  
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @phillipleblanc 
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @Sevenannn 
  - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @sgrebnov 
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @peasee 
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @ewgenius 
  - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/README.md) @Jeadie 
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @phillipleblanc  
  - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @Sevenannn 
  - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @sgrebnov 
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @peasee 
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @ewgenius 
  - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @ewgenius 
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @phillipleblanc 
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @Sevenannn 
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @sgrebnov 
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @peasee 
  - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @ewgenius 
  - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @Jeadie 
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @phillipleblanc 
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @Sevenannn 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls)
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls)
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls)
- [x] Update release notes
  - [x] Ensure any external contributors have been acknowledged.
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md)
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the release branch.
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta`
- [x] Release any docs updates by creating a `v[semver]` tag.
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs.
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow.
- [x] Final test pass on released binaries
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml)
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)
- [x] Create a new branch `release-v[semver]` for the next release version from the current release branch. E.g. `release-v0.17.0-beta`

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

**Comment by Jeadie** [comment]
Issue with quickstart/federation. Only occurs when runtime is still running.
```
2024-09-02T10:29:36.095438Z  WARN runtime: Unable to attach data connector s3: Unable to create dataset acceleration: Acceleration creation failed: Unable to create table: External error: DbConnectionPoolError: ConnectionPoolError: Rusqlite("unable to open database file: /Users/jeadie/Github/quickstarts/federation/.spice/data/s3_source_accelerated_sqlite.db")
```

**Comment by Jeadie** [comment]
E2E Test CI pass on trunk: https://github.com/spiceai/spiceai/actions/runs/10673482283

**Comment by Jeadie** [comment]
Waiting on 
 - https://github.com/spiceai/spiceai/actions/runs/10674297917
 - https://github.com/spiceai/spiceai/actions/runs/10674297887
