### ISSUE TITLE
v0.17.4-beta endgame

### ISSUE THREAD

**Issue by ewgenius** [spiceai/spiceai#2553]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @ewgenius         |
| QA      | @Jeadie           |
| Docs    | @Sevenannn        |
| Comms   | @karifabri        |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | 2nd September          |
| Release      | 9 September            |
| Announcement | 10th September         |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestone/42) @ewgenius 

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk @ewgenius 
- [x] Full test pass and update if necessary over README.md @Sevenannn 
- [x] Full test pass and update if necessary over Docs @Sevenannn 
- [x] Full test pass and update if necessary over existing and new Samples 
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @ewgenius
  - [x] [Local Materialization and Acceleration CQRS] (https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @phillipleblanc 
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @peasee 
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @Jeadie 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @Sevenannn 
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @sgrebnov 
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) @ewgenius 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @phillipleblanc 
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @peasee 
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @Jeadie 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @Sevenannn 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @sgrebnov 
- [x] Full test pass and update if necessary over existing and new Quickstarts
  - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @ewgenius 
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/README.md) @phillipleblanc 
  - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @peasee 
  - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @Jeadie 
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @Sevenannn 
  - [x] [Supabase Data Connector Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @sgrebnov 
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @ewgenius 
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @phillipleblanc 
  - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @peasee 
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @Jeadie 
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @Sevenannn 
  - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/README.md) @sgrebnov 
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @ewgenius 
  - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @phillipleblanc 
  - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @peasee 
  - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) @Jeadie 
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @Sevenannn 
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @sgrebnov 
  - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @ewgenius 
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @phillipleblanc 
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @peasee 
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @Jeadie 
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @Sevenannn 
  - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @sgrebnov 
  - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @ewgenius 
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @phillipleblanc 
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @peasee 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @Sevenannn 
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60) @Sevenannn 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @ewgenius 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @ewgenius 
- [x] Update release notes @ewgenius
  - [x] Ensure any external contributors have been acknowledged. @ewgenius
- [x] Update acknowledgements by triggering [Generate Acknowledgements] (https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md) @Sevenannn 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @ewgenius 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the release branch. @ewgenius 
- [x] QA DRI sign-off @Jeadie 
- [x] Docs DRI sign-off @Sevenannn 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta` @ewgenius 
- [x] Release any docs updates by creating a `v[semver]` tag. @ewgenius 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @ewgenius 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @ewgenius 
- [x] Final test pass on released binaries @ewgenius 
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml) @ewgenius 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @Jeadie 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @sgrebnov 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @peasee 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @ewgenius 
- [x] Create a new branch `release-v[semver]` for the next release version from the current release branch. E.g. `release-v0.17.0-beta` @ewgenius 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)
