### ISSUE TITLE
v0.18.1-beta endgame 

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spiceai#2790]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame |  @sgrebnov                  |
| QA      |  @sgrebnov                  |
| Docs    |  @slyons                  |
| Comms   |   @karifabri                 |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Sept 16 |
| Release      | Mon, Sept 23 |
| Announcement | Tue, Sept 24 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk @sgrebnov 
- [x] Full test pass and update if necessary over README.md @slyons 
- [x] Full test pass and update if necessary over Docs @slyons 
- [x] Full test pass and update if necessary over existing and new Samples
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @Sevenannn 
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @sgrebnov 
  - [x] [Accelerated table data quality with constraint enforcement] (https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @slyons
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @Jeadie 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @peasee 
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @ewgenius  
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) @phillipleblanc 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @Sevenannn 
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @sgrebnov 
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @slyons 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @Jeadie 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @peasee 
- [x] Full test pass and update if necessary over existing and new Quickstarts
  - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @phillipleblanc 
  - [x] [PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/tree/trunk/postgres/connector) @Sevenannn 
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/tree/trunk/postgres/accelerator) @sgrebnov  
  - [x] [DuckDB Data Accelerator](https://github.com/spiceai/quickstarts/tree/trunk/duckdb/accelerator) @slyons  
  - [x]  [SQLite Data Accelerator](https://github.com/spiceai/quickstarts/tree/trunk/acceleration/sqlite) @Jeadie 
  - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @peasee 
  - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @ewgenius 
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @phillipleblanc 
  - [x] [Supabase Data Connector Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @Sevenannn 
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @sgrebnov 
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @slyons 
  - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @Jeadie 
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @peasee 
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @ewgenius 
  - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/README.md) @phillipleblanc 
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @Sevenannn 
  - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @sgrebnov 
  - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @slyons 
  - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) @Jeadie 
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @peasee 
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @ewgenius 
  - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @phillipleblanc 
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @slyons 
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @sgrebnov 
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @slyons 
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @Jeadie 
  - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @peasee 
  - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @ewgenius 
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @phillipleblanc 
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @Sevenannn 
  - [x] [NEW MS SQL quick start](https://github.com/spiceai/quickstarts/tree/trunk/mssql) @sgrebnov
  - [x] [NEW SharePoint Data Connector Quickstart](https://github.com/spiceai/quickstarts/tree/trunk/sharepoint) @slyons 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @slyons 
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60)
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @sgrebnov 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @sgrebnov
- [x] Update release notes @sgrebnov 
  - [x] Ensure any external contributors have been acknowledged.
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md)
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch. @sgrebnov 
- [x] QA DRI sign-off @sgrebnov 
- [x] Docs DRI sign-off @slyons 
- [x] Create a new branch `release-v[semver]` for the release from trunk. E.g. `release-v0.17.0-beta`
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta`
- [x] Release any docs updates by creating a `v[semver]` tag.
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs.
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow.
- [x] Final test pass on released binaries
- [ ] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml)
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

**Comment by eadgbear** [comment]
DuckDB accelerator is blocked on #2589

**Comment by sgrebnov** [comment]
Release is done
