### ISSUE TITLE
v0.18.3-beta endgame

### ISSUE THREAD

**Issue by Jeadie** [spiceai/spiceai#2862]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @Jeadie                   |
| QA      |  @ewgenius   |
| Docs    |  @Sevenannn   |
| Comms   | @karifabri  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon September 23rd |
| Release      | Mon September 30th |
| Announcement | Tue October 1st |

## Planning Checklist
- [ ] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist
- [x] All features/bugfixes to be included in the release have been merged to trunk
- [x] Full test pass and update if necessary over README.md @ewgenius 
- [x] Full test pass and update if necessary over Docs
- [x] Full test pass and update if necessary over existing and new Samples
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) **@sgrebnov**
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) **@slyons**
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) **@Jeadie**
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) **@peasee**
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) **@sgrebnov**
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) **@Sevenannn**
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) **@ewgenius**
  - [x] [Spice with Go SDK sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) **@Jeadie**
  - [x] [Spice with Java SDK sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) **@Sevenannn**
  - [x] [Spice with Rust SDK sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) **@sgrebnov**
  - [x] [Spice with spice.js SDK sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) **@slyons**
  - [x] [Spice with spicepy SDK sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) **@peasee**
- [x] Full test pass and update if necessary over existing and new Quickstarts
    - **Data Connectors:**
    - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) **@sgrebnov**
    - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) **@Jeadie**
    - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) **@ewgenius**
    - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) **@slyons**
    - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) **@Sevenannn**
    - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) **@peasee**
    - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/connector/README.md) **@sgrebnov**
    - [x] [FTP Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/ftp/README.md) **@ewgenius**
    - [x] [File Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/file/README.md) **@Jeadie**
    - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) **@sgrebnov**
    - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) **@sgrebnov**
    - [x] [MSSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mssql/README.md) **@slyons**
    - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) **@Jeadie**
    - [x] [ODBC Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/odbc/README.md) **@peasee**
    - [x] [Planetscale Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/planetscale/README.md) **@peasee**
    - [x] [PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/postgres/connector/README.md) **@slyons**
    - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) **@sgrebnov**
    - [x] [SharePoint Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/sharepoint/README.md) **@ewgenius**
    - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) **@slyons**
    - [x] [Spark Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spark/README.md) **@sgrebnov**
    - [x] [Supabase Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) **@peasee**
    - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) **@Sevenannn**
    - **Data Accelerators:**
    - [x] [DuckDB Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/accelerator/README.md) **@ewgenius**
    - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/accelerator/README.md) **@Sevenannn**
    - [x] [SQLite Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/sqlite/accelerator/README.md) **@Jeadie**
    - **Catalog Connectors:**
    - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) **@sgrebnov**
    - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) **@peasee**
    - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) **@slyons**
    - **Other Quickstarts:**
    - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) **@Sevenannn**
    - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) **@Jeadie**
    - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) **@ewgenius**
    - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) **@slyons**
    - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) **@sgrebnov**
    - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) **@peasee**
    - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) **@Jeadie**
    - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) **@sgrebnov**
    - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) **@sgrebnov**
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls)
  - [x] #2909
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls)
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls)
- [x] Update release notes
  - [x] Ensure any external contributors have been acknowledged.
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md)
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch.
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Create a new branch `release-v[semver]` for the release from trunk. E.g. `release-v0.17.0-beta`
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta`
- [x] Release any docs updates by creating a `v[semver]` tag.
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs.
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow.
- [x] Final test pass on released binaries
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml)
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

**Comment by Jeadie** [comment]
E2E test CI: https://github.com/spiceai/spiceai/actions/runs/11116220560

**Comment by Jeadie** [comment]
- build_and_release: https://github.com/spiceai/spiceai/actions/runs/11116999014
- spiced_docker: https://github.com/spiceai/spiceai/actions/runs/11116999015
