### ISSUE TITLE
v0.19.0-beta endgame

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#2981]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @peasee |
| QA      | @Jeadie |
| Docs    | @sgrebnov |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon September 30th |
| Release      | Mon October 7th |
| Announcement | Tue October 8th |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk
- [x] Full test pass and update if necessary over README.md @Jeadie 
- [x] Full test pass and update if necessary over Docs @sgrebnov 
- [x] Full test pass and update if necessary over existing and new Samples
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @ewgenius 
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @Jeadie 
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @Sevenannn 
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @sgrebnov 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @Sevenannn 
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @ewgenius 
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) @phillipleblanc 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @slyons 
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @peasee 
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @Jeadie 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @phillipleblanc 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @slyons 
- [x] Full test pass and update if necessary over existing and new Quickstarts
    - **Data Connectors:**
    - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @phillipleblanc 
    - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @Sevenannn 
    - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @sgrebnov 
    - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @ewgenius 
    - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @slyons 
    - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @sgrebnov 
    - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/connector/README.md) @Jeadie 
    - [x] [FTP Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/ftp/README.md) @ewgenius 
    - [x] [File Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/file/README.md) @phillipleblanc 
    - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) @slyons 
    - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @sgrebnov 
    - [x] [MSSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mssql/README.md) @Sevenannn 
    - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @peasee 
    - [x] [ODBC Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/odbc/README.md) @phillipleblanc 
    - [x] [Planetscale Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/planetscale/README.md) @Jeadie 
    - [x] [PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/postgres/connector/README.md) @Sevenannn 
    - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @ewgenius 
    - [x] [SharePoint Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/sharepoint/README.md) @phillipleblanc 
    - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @peasee 
    - [x] [Spark Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spark/README.md) @slyons 
    - [x] [Supabase Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @ewgenius 
    - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @Sevenannn 
    - **Data Accelerators:**
    - [x] [DuckDB Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/accelerator/README.md) @sgrebnov 
    - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/accelerator/README.md) @Jeadie 
    - [x] [SQLite Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/sqlite/accelerator/README.md) @phillipleblanc 
    - **Catalog Connectors:**
    - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @slyons 
    - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @Jeadie 
    - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @sgrebnov 
    - **Other Quickstarts:**
    - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @Sevenannn 
    - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @sgrebnov 
    - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @Jeadie 
    - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @phillipleblanc 
    - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @peasee 
    - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @slyons 
    - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @ewgenius 
    - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @slyons 
    - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @sgrebnov 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @sgrebnov 
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60) @sgrebnov 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @peasee 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @peasee 
- [x] Update release notes @peasee 
  - [x] Ensure any external contributors have been acknowledged. @peasee 
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius 
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md) @ewgenius 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @Sevenannn 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch. @Jeadie 
- [x] QA DRI sign-off @Jeadie 
- [x] Docs DRI sign-off @sgrebnov 
- [x] Create a new branch `release-v[semver]` for the release from trunk. E.g. `release-v0.17.0-beta` @peasee 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta` @peasee 
- [x] Release any docs updates by creating a `v[semver]` tag. @peasee 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @sgrebnov 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @peasee
- [x] Final test pass on released binaries @Jeadie 
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml) @peasee 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @Jeadie 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @peasee 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @peasee 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @peasee 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)

**Comment by Jeadie** [comment]
E2E test CI: https://github.com/spiceai/spiceai/actions/runs/11225179800
