### ISSUE TITLE
Enhancement: Run Clickbench for Spice RC Accelerators

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#3246]
\*REMEMBER, BE **SMART**!

S: Specific
M: Measurable
A: Achievable
R: Relevant
T: Time-Bound\*

## Goal-State/What/Result

Clickbench queries are running automatically for selected RC1 release accelerators as part of benchmark test scheduled every Wed, Fri, Sat, Sun. 
- DuckDB Data Accelerator
- Arrow Data Accelerator

Grafana Dashboards are added to automatically update Clickbench queries success / failure status and performance statistics based on Clickbench results.

## Why/Purpose

Enabling Clickbench serves as a proof of Spice accelerators achieving RC quality. The benchmark tests evaluates the Clickbench workflow support and performance across accelerators. The Dashboard provide direct measurement on Clickbench workflow support & performance statistics overtime, ensuring the non-degrading performance over time.

## By When

_A target date for done-done completion of the entire enhancement._

**Issue/Spec written and reviewed:** Nov 4th
**Done-Done:** Nov 11th

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

## Spec

- Clickbench is included as part of Spice Runtime benchmark Rust program and can be executed with: `<benchmark_binary>  -b clickbench -a accelerator`.
- Clickbench of RC accelerators are run with separate runner with greater resource limit in benchmarks workflow.
- Clickbench Dashboards include the overview dashboard for performance & clickbench workflow support, and individual dashbaords for test duration & individual query execution duration. 

### First Principle
 - Align to Industry Standards

### Security Review
- User will not be allowed to specify arbitrary inputs to github workflow, the runner / workflow will not be compromised.

### Requirements
  - Clickbench will built on the existing benchmark system that serves TPCH & TPCDS benchmarks in Spice to keep the consistency in benchmarking.
  - New runner with greater memory is needed to support clickbench workflow (Clickbench data size is ~70GB) 
  - Accelerator Clickbench will use S3 as a data source

### Scope
  - This enhancements only adds clickbench for accelerators required for v1.0.0-rc1 release. Clickbench for accelerators promoted to RC quality later will need to be added manually by the DRI of RC enhancement.
  - Include Spice in [Clickbench Scoreboard](https://benchmark.clickhouse.com) is scoped out as a separate enhancement, and this enhancement will not adopt a pure shell script based approach for running Clickbench.
  - Clickbench Scoreboard specific measurements, e.g. `load time`, `data size` will not be measured in this enhancements, as these are measured manually as separate component from running queries script in [Clickbench repo](https://github.com/ClickHouse/ClickBench), i.e. these specs are checked manually from log in per database and are not part of the run clickbench script. Also these are not required for achieving the goal of this enhancement - Validate support and record query performance for Clickbench in Spice

### Automation
  - Clickbench is automated to run using github workflow
  - Grafana Dashboards automatically updates based on benchmark results

### Milestone
  - M1: Benchmark Binary is refactored to run Clickbench.
  - M2: Clickbench is included as part of benchmark workflow.
  - M3: Clickbench dashboards are added to Grafana.

### Implementation (Sub Issues)

- Sub Issue 1
- Sub Issue 2

### QA

- Sub Issue 1
- Sub Issue 2
