### ISSUE TITLE
v0.19.3-beta endgame

### ISSUE THREAD

**Issue by Sevenannn** [spiceai/spiceai#3253]
## DRIs

|         | DRI |
| ------- | --- |
| Endgame |  @sgrebnov    |
| QA      |  @sgrebnov    |
| Docs    |  @peasee    |
| Comms   |  @karifabri    |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Oct 21 |
| Release      | Mon, Oct 28 |
| Announcement | Tue, Oct 29 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All features/bugfixes to be included in the release have been merged to trunk @sgrebnov 
- [x] Full test pass and update if necessary over README.md @sgrebnov 
- [x] Full test pass and update if necessary over Docs @peasee 
- [x] Full test pass and update if necessary over existing and new Samples
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @slyons 
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @Jeadie 
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @sgrebnov  
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @ewgenius 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @phillipleblanc 
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @sgrebnov 
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/data-connectors/README.md) @slyons 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @sgrebnov 
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @peasee 
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @Jeadie 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @ewgenius 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @phillipleblanc 
- [x] Full test pass and update if necessary over existing and new Quickstarts
  - **Data Connectors:**
  - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @sgrebnov 
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @slyons 
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @sgrebnov 
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @peasee 
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @Jeadie 
  - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @ewgenius 
  - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/connector/README.md) @phillipleblanc 
  - [x] [FTP Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/ftp/README.md) @sgrebnov 
  - [x] [File Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/file/README.md) @slyons 
  - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) @sgrebnov  
  - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @peasee 
  - [x] [MSSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mssql/README.md) @Jeadie 
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @ewgenius 
  - [x] [ODBC Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/odbc/README.md) @phillipleblanc 
  - [x] [Planetscale Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/planetscale/README.md) @sgrebnov 
  - [x] [PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/postgres/connector/README.md) @slyons 
  - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @sgrebnov 
  - [x] [SharePoint Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/sharepoint/README.md) @peasee 
  - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @Jeadie 
  - [x] [Spark Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spark/README.md) @ewgenius 
  - [x] [Supabase Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @phillipleblanc 
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @slyons 
  - [x] Update the RC status of any connectors based on the [criteria](/docs/criteria/connectors/rc.md) @sgrebnov 
  - **Data Accelerators:**
  - [x] [DuckDB Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/accelerator/README.md) @sgrebnov 
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/accelerator/README.md) @peasee 
  - [x] [SQLite Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/sqlite/accelerator/README.md) @Jeadie 
  - [x] Update the Beta status of any accelerators based on the [criteria](/docs/criteria/accelerators/beta.md) @sgrebnov 
  - **Catalog Connectors:**
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @ewgenius 
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @phillipleblanc 
  - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @sgrebnov 
  - **Other Quickstarts:**
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @slyons 
  - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @sgrebnov  
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @peasee 
  - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @Jeadie 
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @ewgenius 
  - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @phillipleblanc 
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @sgrebnov 
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @slyons 
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @sgrebnov 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @peasee 
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60) @peasee 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @Jeadie 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @ewgenius 
- [x] Update release notes  @sgrebnov 
  - [x] Ensure any external contributors have been acknowledged. @sgrebnov 
- [x] Add any SDK releases to the release notes @peasee 
  - [x] [spice.js](https://github.com/spiceai/spice.js/releases)
  - [x] [spicepy](https://github.com/spiceai/spicepy/releases)
  - [x] [spice-rs](https://github.com/spiceai/spice-rs/releases)
  - [x] [spice-java](https://github.com/spiceai/spice-java/releases)
  - [x] [spice-dotnet](https://github.com/spiceai/spice-dotnet/releases)
  - [x] [gospice](https://github.com/spiceai/gospice/releases)
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @phillipleblanc 
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md) @phillipleblanc 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @sgrebnov 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch. @slyons 
- [x] QA DRI sign-off @sgrebnov 
- [x] Docs DRI sign-off @peasee 
- [x] Create a new branch `release-v[semver]` for the release from trunk. E.g. `release-v0.17.0-beta` @sgrebnov  
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.17.0-beta`. Leave the release note empty; the automation will fill it in from the checked in release note. @sgrebnov  
- [x] Release any docs updates by creating a `v[semver]` tag. @sgrebnov  
      **Note**: Docs should be released only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml). @sgrebnov 
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @sgrebnov  
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @ewgenius 
      **Note**: Release chart workflow should be triggered only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml) and [docker image have finished building](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml).
- [x] Final test pass on released binaries @sgrebnov 
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml) @sgrebnov 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)  @sgrebnov  
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @sgrebnov 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai).
      **Note**: Ensure that the Homebrew taps are updated only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml). @sgrebnov 
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @sgrebnov 
- [x] Set the [release](https://github.com/spiceai/spiceai/releases) as latest release. @sgrebnov  

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)
