### ISSUE TITLE
Enhancement: Eval datasets

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#3320]
## Goal-State/What/Result
Users of `spice` can run their models against an evaluation dataset, have the model's outputs compared and scored, and track these model evaluations over time. 

## Why/Purpose

Being able to evaluate a model's performance is critical for users to be able to deploy AI systems to produce and to continue to trust and improve their outputs.

## By When

**Issue/Spec written and reviewed:** Tue 3rd December
**M1 Done-Done:** 10th December
**Done-Done:** <Target Date>

## Done-Done

- [x] [First Principles Driven](https://github.com/spiceai/spiceai/blob/trunk/docs/PRINCIPLES.md)
- [x] The Algorithm
- [x] PM/Design Review
- [x] DX/UX Review
- [x] Threat Model / Security Review
- [x] Tests
- [x] Performance / Benchmarks
- [x] Documentation
- [x] Samples/Quickstarts/Tutorials
- [x] Release Notes

## The Algorithm

- [x] Every requirement questioned?
- [x] Delete (Scope) any part you can.
- [x] Simplify.
- [x] Break down into smaller iterations/milestones.
- [x] Opportunities for automation.

### Eval Dataset
**What is an eval Dataset?**
An input:
 - Complete OpenAI API request body.
 - `.messages` to use in OpenAI API request body.
 - `.messages[].content` for first `"role": "user"` message.

Similar with output:
 - Complete OpenAI API response body.
 - `.choices[0].message` returned from OpenAI API response body.
 - `.choices[0].message.content` for first `"role": "assistant"` message.

To an extent, this can be inferred.
- [`openai/eval`](https://github.com/openai/evals) uses:
  - `.messages` inputs
  - `.choices[0].message.content[?(@.role = 'assistant')]` outputs.

**Creating an eval dataset**

As a dataset:
```yaml
datasets:
  - name: abstract2title
    from: file:/Users/jeadie/Downloads/abstract2title.jsonl
```

From `runtime.task_history`:
```yaml
views:
  - name: eval_from_openai
    sql: |
      SELECT input, captured_output
      FROM runtime.task_history
      WHERE
          task='ai_chat'
        AND
          map_extract(labels, 'model')[1] = 'oai'
```

Add/update to a dataset (possibly a sink) programatically via an API:
```shell
curl TODO
```

### Eval Run
 - A model, run against a eval dataset, with a set of scoring functions.
 - The results of which are stored in a `runtime.eval_results` table.
   - input, output, ideal, score_a, score_b, ... (for each scoring function).
 - The metadata pertaining to the eval run a `runtime.eval_runs` table.
  - To avoid changes in Spice definitions, record the the Spicepod component of:
    - The `model` tested
    - The `scorer`(s) used 

To run the `loves_cricket` evaluation against the `oai` model. 

```shell
curl -XPOST "http://localhost:8080/v1/eval/loves_cricket/run" -d '{"model": "oai"}'
```

### Eval DX
- Example from [openai/evals](https://github.com/openai/evals/blob/main/evals/registry/evals/abstract2title.yaml):
```yaml
abstract2title:
  id: abstract2title.test.v1
  metrics: [accuracy] # i.e. metrics, dependent on eval `.class`.
  description: Test the model's ability to generate proper title using the abstract section of the literature.

abstract2title.test.v1:
  class: evals.elsuite.modelgraded.classify:ModelBasedClassify # Python class to run the evaluation
  args:
    samples_jsonl: abstract2title/samples.jsonl # pointer to a dataset
    modelgraded_spec: closedqa # pointer to a spiced scorer component
    modelgraded_spec_args:
      criteria: "conciseness: Does the title properly describe the provided content?"

abstract2title.qa.v1.1:
 ...
```

Where `modelgraded_spec` is a reference to a separate scorer (see [below](#eval-scoring)).

For Spice, a simple initial spec to define an eval
```yaml
datasets:
  - name: cricket_logic
    from: file:samples.jsonl

evals:
 - name: loves_cricket
    description: |
      Make sure any LLM we use is truly Australian
    dataset: cricket_logic
    scorers:
      - Match
      - WithoutToolUse
```

### Eval Scoring
Roughly:
```rust
   fn scoring_fn(input: Value, actual: Value, ideal: Value) -> f32;
```

Model graded scorers have a specific UX (in `openai/evals`), in this [example](https://github.com/openai/evals/blob/main/evals/registry/modelgraded/closedqa.yaml):
```yaml
closedqa:
  prompt: |-
    You are assessing a submitted answer on a given task based on a criterion. Here is the data:
    [BEGIN DATA]
    ***
    [Task]: {input}
    ***
    [Submission]: {completion}
    ***
    [Criterion]: {criteria}
    ***
    [END DATA]
    Does the submission meet the criterion? First, write out in a step by step manner your reasoning about the criterion to be sure that your conclusion is correct. Avoid simply stating the correct answers at the outset. Then print only the single character "Y" or "N" (without quotes or punctuation) on its own line corresponding to the correct answer. At the end, repeat just the letter again by itself on a new line.

    Reasoning:
  eval_type: cot_classify
  choice_scores:
    "Y": 1.0
    "N": 0.0
  choice_strings: 'YN'
  input_outputs:
    input: "completion"
```
 - The above UX suggests a way `scorer` spiced component that augments an existing `model` component.
 - TODO: define UX for model graded scorers. 
```yaml
scorers:
  - name: foo
    from: models:oai
    prompt: | 
      ... with templating
    eval_type: cot_classify
    params:
      choice_scores:
        "Y": 1.0
        "N": 0.0
      choice_strings: 'YN'
      input_outputs:
        input: "completion"
```
### Milestones
1. Run a model against an eval dataset, with predefined, not LLM-based, scoring functions.
 - `spice.evals.runs` table.
 - `spice.evals.results` table
 - API/CLI to start an eval run.
 - `eval` spec parsing (possibly as spice component).

2. LLM-based scoring functions.
 - `scorer` spiced component, serialised into `runtime.eval_runs`.

3. Non-dataset based Evals:
  - 

### QA

- Sub Issue 1
- Sub Issue 2

**Comment by Jeadie** [comment]
Questions from discussion:
 - Persistence of `spice.evals.*`. e.g. replication.

**Comment by sgrebnov** [comment]
target outcome: done-done

**Comment by Jeadie** [comment]
might need to attempt to parse jsons str from input/output.

**Comment by Jeadie** [comment]
### spice.evals.results
```
run_id, input, output, actual, scorer, value
```

**Comment by Sevenannn** [comment]
EOW Goal: M1 done, all functionalities needed for board demo are done

**Comment by lukekim** [comment]
- M1 done (except for docs?)
- M2 target for RC.3

**Comment by Jeadie** [comment]
Current: M1 code complete. API docs in review. 
This week: Cookbook, conceptual docs, UX for LLM scorers. 

Lesser priority that #3925

**Comment by sgrebnov** [comment]
Must be transformed as part of benchmarking to identify gaps

**Comment by lukekim** [comment]
Create new Enhancement for model grading, and complete this issue done-done.
