### ISSUE TITLE
v1.0-rc.2 endgame

### ISSUE THREAD

**Issue by peasee** [spiceai/spiceai#3865]
## DRIs

|         | DRI |
| ------- | --- |
| Endgame |  @peasee |
| QA      |  @Jeadie |
| Docs    |  @sgrebnov |
| Comms   | @karifabri |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Nov 25th  |
| Release      | Mon, Dec 16th |
| Announcement | Tue, Dec 17th |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] Create the release branch (`release-X.Y`) from `trunk` one day before the scheduled release (if not already created). @peasee 
  - See [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md) for more details.
- [x] All features/bugfixes to be included in the release have been fast-forwarded/cherry-picked to the release branch. @peasee 
- [x] Full test pass and update if necessary over README.md @Jeadie 
- [x] Full test pass and update if necessary over Docs @sgrebnov 
- [x] Full test pass and update if necessary over existing and new Samples  
  - [x] [Sales BI Dashboard](https://github.com/spiceai/samples/blob/trunk/sales-bi/README.md) @phillipleblanc  
  - [x] [Local Materialization and Acceleration CQRS](https://github.com/spiceai/samples/blob/trunk/acceleration/README.md) @ewgenius  
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/samples/blob/trunk/constraints/README.md) @Jeadie  
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/samples/blob/trunk/cdc-debezium/README.md) @sgrebnov  
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/samples/blob/trunk/tls/README.md) @peasee  
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/samples/blob/trunk/grafana-datasource/README.md) @Sevenannn  
  - [x] [FTP/SFTP Data Connector](https://github.com/spiceai/samples/blob/trunk/ftp/README.md) @phillipleblanc  
  - [x] [Spice with go sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @ewgenius  
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @Jeadie  
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @sgrebnov  
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @peasee  
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/samples/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @Sevenannn  
  - [x] [Spice with the OpenAI SDK](https://github.com/spiceai/samples/tree/trunk/spice_openai_sdk) @phillipleblanc  

- [x] Full test pass and update if necessary over existing and new Quickstarts  
  - **Data Connectors:**  
  - [x] [Apache Superset](https://github.com/spiceai/quickstarts/blob/trunk/superset/README.md) @ewgenius  
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-aurora-mysql/README.md) @sgrebnov 
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/rds-postgresql/README.md) @sgrebnov  
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/clickhouse/README.md) @peasee  
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/databricks/README.md) @Sevenannn  
  - [x] [Dremio Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/dremio/README.md) @phillipleblanc  
  - [x] [DuckDB Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/connector/README.md) @ewgenius  
  - [x] [FTP Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/ftp/README.md) @phillipleblanc 
  - [x] [File Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/file/README.md) @sgrebnov  
  - [x] [GitHub Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/github/README.md) @peasee  
  - [x] [GraphQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/graphql/README.md) @Sevenannn  
  - [x] [MSSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mssql/README.md) @phillipleblanc  
  - [x] [MySQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/mysql/README.md) @peasee  
  - [x] [ODBC Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/odbc/README.md) @peasee 
  - [x] ~[Planetscale Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/planetscale/README.md)~ -@sgrebnov  (skipped, no shared account available)
  - [x] [PostgreSQL Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/postgres/connector/README.md) @peasee  
  - [x] [S3 Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/s3/README.md) @Sevenannn  
  - [x] [SharePoint Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/sharepoint/README.md) @phillipleblanc  
  - [x] [Snowflake Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/snowflake/README.md) @sgrebnov 
  - [x] [Spark Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spark/README.md) @Sevenannn 
  - [x] [Supabase Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/supabase/README.md) @sgrebnov  
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/quickstarts/blob/trunk/spiceai/README.md) @ewgenius  
  - [x] Update the RC status of any connectors based on the [criteria](/docs/criteria/connectors/rc.md) @peasee
  - **Data Accelerators:**  
  - [x] [DuckDB Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/duckdb/accelerator/README.md) @phillipleblanc  
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/postgres/accelerator/README.md) @ewgenius  
  - [x] [SQLite Data Accelerator](https://github.com/spiceai/quickstarts/blob/trunk/sqlite/accelerator/README.md) @ewgenius 
  - [x] Update the Beta status of any accelerators based on the [criteria](/docs/criteria/accelerators/beta.md) @peasee
  - **Catalog Connectors:**  
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/databricks/README.md) @peasee  
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/spiceai/README.md) @ewgenius  
  - [x] [Unity Catalog Connector](https://github.com/spiceai/quickstarts/blob/trunk/catalogs/unity_catalog/README.md) @phillipleblanc  
  - **AI/ML Models:**  
  - [x] [Searching GitHub files with Spice](https://github.com/spiceai/quickstarts/tree/trunk/search_github_files) @ewgenius  
  - [x] [Text-to-SQL with Spicel](https://github.com/spiceai/quickstarts/tree/trunk/text-to-sql) @Jeadie  
  - [x] [Spice with Azure OpenAI](https://github.com/spiceai/quickstarts/tree/trunk/azure_openai) @sgrebnov  
  - **Other Quickstarts:**  
  - [x] [Advanced Data Refresh](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/data-refresh/README.md) @peasee  
  - [x] [Data Retention Policy](https://github.com/spiceai/quickstarts/blob/trunk/retention/README.md) @Sevenannn  
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/quickstarts/blob/trunk/kubernetes/README.md) @phillipleblanc  
  - [x] [Federated SQL Query](https://github.com/spiceai/quickstarts/blob/trunk/federation/README.md) @ewgenius  
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/quickstarts/blob/trunk/acceleration/indexes/README.md) @Jeadie  
  - [x] [Refresh Data Window](https://github.com/spiceai/quickstarts/blob/trunk/refresh-data-window/README.md) @sgrebnov  
  - [x] [Results Caching](https://github.com/spiceai/quickstarts/blob/trunk/caching/README.md) @peasee  
  - [x] [Securing data in transit via TLS](https://github.com/spiceai/quickstarts/blob/trunk/tls/README.md) @Sevenannn  
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/quickstarts/blob/trunk/tpc-h/README.md) @phillipleblanc  
  - [x] [API Key Authentication](https://github.com/spiceai/quickstarts/blob/trunk/api_key/README.md) @ewgenius  

- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @sgrebnov 
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60) @sgrebnov 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @Jeadie 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/quickstarts/pulls) @Jeadie 
- [x] Update release notes @peasee 
  - [x] Ensure any external contributors have been acknowledged. @peasee 
- [x] Add any SDK releases to the release notes @peasee 
  - [x] [spice.js](https://github.com/spiceai/spice.js/releases) @peasee 
  - [x] [spicepy](https://github.com/spiceai/spicepy/releases) @peasee 
  - [x] [spice-rs](https://github.com/spiceai/spice-rs/releases) @peasee 
  - [x] [spice-java](https://github.com/spiceai/spice-java/releases) @peasee 
  - [x] [spice-dotnet](https://github.com/spiceai/spice-dotnet/releases) @peasee 
  - [x] [gospice](https://github.com/spiceai/gospice/releases) @peasee 
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @sgrebnov 
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md) @sgrebnov 
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @peasee 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch. @Jeadie 
- [x] QA DRI sign-off @Jeadie 
- [x] Docs DRI sign-off @sgrebnov 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v1.0.0-rc.1`. Leave the release note empty; the automation will fill it in from the checked in release note. @peasee 
- [x] Release any docs updates by creating a `v[semver]` tag. @peasee 
      **Note**: Docs should be released only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml).
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs. @peasee 
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow. @peasee 
      **Note**: Release chart workflow should be triggered only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml) and [docker image have finished building](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml).
- [x] Final test pass on released binaries @Jeadie 
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml) @peasee 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @Jeadie 
- [x] Update `version.txt` and version in `Cargo.toml` to the next scheduled release version. @peasee 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai). @peasee 
      **Note**: Ensure that the Homebrew taps are updated only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml).
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md) @peasee 
- [x] Update supported version in SECURITY.md @peasee 
- [x] Set the [release](https://github.com/spiceai/spiceai/releases) as latest release. @peasee 

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai) @karifabri 
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @karifabri 
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf) @karifabri 
- [x] Telegram: [spiceai](https://t.me/spiceai) @karifabri 
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @karifabri
