### ISSUE TITLE
v0.1.0-rc.3 endgame

### ISSUE THREAD

**Issue by lukekim** [spiceai/spiceai#4066]
## DRIs

|         | DRI |
| ------- | --- |
| Endgame |   @lukekim  |
| QA      |  @peasee    |
| Docs    |  @Jeadie     |
| Comms   |   @karifabri   |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon Dec 23, 2024 |
| Release      | Mon Dec 30, 2024 |
| Announcement | Tue Dec 31, 2024 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] Create the release branch (`release-X.Y`) from `trunk` one day before the scheduled release (if not already created).
  - See [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md) for more details.
- [x] All features/bugfixes to be included in the release have been fast-forwarded/cherry-picked to the release branch.
- [x] Full test pass and update if necessary over README.md @peasee 
- [x] Full test pass and update if necessary over Docs @Jeadie 
- [x] Full test pass and update if necessary over existing and new Cookbook recipes @Jeadie 
    - **Data Connectors:**
  - [x] [AWS RDS Aurora (MySQL Compatible) Data Connector](https://github.com/spiceai/cookbook/blob/trunk/mysql/rds-aurora/README.md) @peasee
  - [x] [AWS RDS PostgreSQL Data Connector](https://github.com/spiceai/cookbook/blob/trunk/postgres/rds/README.md) @jeadie
  - [x] [Clickhouse Data Connector](https://github.com/spiceai/cookbook/blob/trunk/clickhouse/README.md) @phillipleblanc
  - [x] [Databricks Delta Lake Data Connector](https://github.com/spiceai/cookbook/blob/trunk/databricks/delta_lake/README.md) @sevenann
  - [x] [Dremio Data Connector](https://github.com/spiceai/cookbook/blob/trunk/dremio/README.md) @ewgenius 
  - [x] [DuckDB Data Connector](https://github.com/spiceai/cookbook/blob/trunk/duckdb/connector/README.md) @jeadie
  - [x] [FTP Data Connector](https://github.com/spiceai/cookbook/blob/trunk/ftp/README.md) @phillipleblanc
  - [x] [File Data Connector](https://github.com/spiceai/cookbook/blob/trunk/file/README.md) @ewgenius 
  - [x] [GitHub Data Connector](https://github.com/spiceai/cookbook/blob/trunk/github/README.md) @peasee
  - [x] [GraphQL Data Connector](https://github.com/spiceai/cookbook/blob/trunk/graphql/README.md) @jeadie
  - [x] [MSSQL Data Connector](https://github.com/spiceai/cookbook/blob/trunk/mssql/README.md) @phillipleblanc
  - [x] [MySQL Data Connector](https://github.com/spiceai/cookbook/blob/trunk/mysql/connector/README.md) @sevenann
  - [x] [ODBC Data Connector](https://github.com/spiceai/cookbook/blob/trunk/odbc/README.md) @peasee
  - [x] [Planetscale Recipe](https://github.com/spiceai/cookbook/blob/trunk/mysql/planetscale/README.md) @jeadie
  - [x] [PostgreSQL Data Connector](https://github.com/spiceai/cookbook/blob/trunk/postgres/connector/README.md) @phillipleblanc
  - [x] [S3 Data Connector](https://github.com/spiceai/cookbook/blob/trunk/s3/README.md) @sevenann
  - [x] [SharePoint Data Connector](https://github.com/spiceai/cookbook/blob/trunk/sharepoint/README.md) @ewgenius 
  - [x] [Snowflake Data Connector](https://github.com/spiceai/cookbook/blob/trunk/snowflake/README.md) @jeadie
  - [x] [Spark Data Connector](https://github.com/spiceai/cookbook/blob/trunk/spark/README.md) @phillipleblanc
  - [x] [Supabase Data Connector](https://github.com/spiceai/cookbook/blob/trunk/postgres/supabase/README.md) @ewgenius
  - [x] [Spice.ai Cloud Platform Data Connector](https://github.com/spiceai/cookbook/blob/trunk/spiceai/README.md) @peasee
  - [x] [Streaming changes in real-time with Debezium CDC](https://github.com/spiceai/cookbook/blob/trunk/cdc-debezium/README.md) @jeadie
  - [x] [Streaming changes in real-time with Debezium CDC (SASL/SCRAM)](https://github.com/spiceai/cookbook/blob/trunk/cdc-debezium/sasl-scram/README.md) @phillipleblanc
  - [x] Update the status of any connectors based on the [criteria](/docs/criteria/connectors/rc.md) @peasee
- **Data Accelerators:**
  - [x] [DuckDB Data Accelerator](https://github.com/spiceai/cookbook/blob/trunk/duckdb/accelerator/README.md) @peasee
  - [x] [PostgreSQL Data Accelerator](https://github.com/spiceai/cookbook/blob/trunk/postgres/accelerator/README.md) @jeadie
  - [x] [SQLite Data Accelerator](https://github.com/spiceai/cookbook/blob/trunk/sqlite/accelerator/README.md) @phillipleblanc
  - [x] [Arrow Data Accelerator](https://github.com/spiceai/cookbook/blob/trunk/arrow/README.md) @sevenann
  - [x] Update the status of any accelerators based on the [criteria](/docs/criteria/accelerators/rc.md) @peasee
- **Catalog Connectors:**
  - [x] [Databricks Unity Catalog Connector](https://github.com/spiceai/cookbook/blob/trunk/catalogs/databricks/README.md) @jeadie
  - [x] [Spice.ai Cloud Platform Catalog Connector](https://github.com/spiceai/cookbook/blob/trunk/catalogs/spiceai/README.md) @phillipleblanc
  - [x] [Unity Catalog Connector](https://github.com/spiceai/cookbook/blob/trunk/catalogs/unity_catalog/README.md) @sevenann
  - [x] [Iceberg Catalog Connector]() @peasee 
- **AI/ML Models:**
  - [x] [Searching GitHub files with Spice](https://github.com/spiceai/cookbook/tree/trunk/search_github_files) @peasee
  - [x] [Text-to-SQL (NSQL)](https://github.com/spiceai/cookbook/tree/trunk/nsql) @jeadie
  - [x] [Text-to-SQL (Tools)](https://github.com/spiceai/cookbook/tree/trunk/text-to-sql) @phillipleblanc
  - [x] [Spice with Azure OpenAI](https://github.com/spiceai/cookbook/tree/trunk/azure_openai) @sevenann
  - [x] [OpenAI SDK](https://github.com/spiceai/cookbook/tree/trunk/openai_sdk) @ewgenius 
  - [x] [Nvidia NIM](https://github.com/spiceai/cookbook/tree/trunk/nvidia-nim) @jeadie
  - [x] [LLM Memory](https://github.com/spiceai/cookbook/tree/trunk/llm-memory) @phillipleblanc
- **Other cookbook recipes:**
  - [x] [Sales BI (Apache Superset)](https://github.com/spiceai/cookbook/blob/trunk/sales-bi/README.md) @ewgenius
  - [x] [Accelerated table data quality with constraint enforcement](https://github.com/spiceai/cookbook/blob/trunk/acceleration/constraints/README.md) @peasee
  - [x] [Advanced Data Refresh](https://github.com/spiceai/cookbook/blob/trunk/acceleration/data-refresh/README.md) @jeadie
  - [x] [Data Retention Policy](https://github.com/spiceai/cookbook/blob/trunk/retention/README.md) @ewgenius 
  - [x] [Deploying to Kubernetes](https://github.com/spiceai/cookbook/blob/trunk/kubernetes/README.md) @ewgenius
  - [x] [Federated SQL Query](https://github.com/spiceai/cookbook/blob/trunk/federation/README.md) @peasee
  - [x] [Indexes on Accelerated Data](https://github.com/spiceai/cookbook/blob/trunk/acceleration/indexes/README.md) @jeadie
  - [x] [Refresh Data Window](https://github.com/spiceai/cookbook/blob/trunk/refresh-data-window/README.md) @ewgenius
  - [x] [Results Caching](https://github.com/spiceai/cookbook/blob/trunk/caching/README.md) @ewgenius 
  - [x] [Encryption in transit using TLS](https://github.com/spiceai/cookbook/blob/trunk/tls/README.md) @peasee
  - [x] [TPC-H Benchmarking](https://github.com/spiceai/cookbook/blob/trunk/tpc-h/README.md) @ewgenius 
  - [x] [API Key Authentication](https://github.com/spiceai/cookbook/blob/trunk/api_key/README.md) @phillipleblanc
  - [x] [Adding Spice as a Grafana datasource](https://github.com/spiceai/cookbook/blob/trunk/grafana-datasource/README.md) @ewgenius 
  - [x] [Spice with go sdk sample](https://github.com/spiceai/cookbook/blob/trunk/client-sdk/gospice-sdk-sample/README.md) @peasee
  - [x] [Spice with Java sdk sample](https://github.com/spiceai/cookbook/blob/trunk/client-sdk/spice-java-sdk-sample/README.md) @jeadie
  - [x] [Spice with rust sdk sample](https://github.com/spiceai/cookbook/blob/trunk/client-sdk/spice-rs-sdk-sample/README.md) @ewgenius 
  - [x] [Spice with spice.js sdk sample](https://github.com/spiceai/cookbook/blob/trunk/client-sdk/spice.js-sdk-sample/README.md) @ewgenius 
  - [x] [Spice with spicepy sdk sample](https://github.com/spiceai/cookbook/blob/trunk/client-sdk/spicepy-sdk-sample/README.md) @peasee
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls)
  - [x] Update spice version in [docs banner](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docusaurus.config.ts#L60)
- [x] Merge [Cookbook PRs](https://github.com/spiceai/cookbook/pulls)
- [x] Update release notes
  - [x] Ensure any external contributors have been acknowledged.
  - [x] Ensure notable dependency updates have been included in the release notes (`datafusion`, `datafusion-table-providers`, etc) under the `## Dependencies` header
  - [x] Ensure any changes to the [cookbook](https://github.com/spiceai/cookbook) have been included in the release notes under the `## Cookbook` header
- [x] Add any SDK releases to the release notes
  - [x] [spice.js](https://github.com/spiceai/spice.js/releases)
  - [x] [spicepy](https://github.com/spiceai/spicepy/releases)
  - [x] [spice-rs](https://github.com/spiceai/spice-rs/releases)
  - [x] [spice-java](https://github.com/spiceai/spice-java/releases)
  - [x] [spice-dotnet](https://github.com/spiceai/spice-dotnet/releases)
  - [x] [gospice](https://github.com/spiceai/gospice/releases)
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow
  - [x] Update acknowledgements in [docs](https://github.com/spiceai/docs/blob/trunk/spiceaidocs/docs/acknowledgements/index.md)
- [x] Verify `version.txt` and version in `Cargo.toml` are correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on the trunk branch.
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v1.0.0-rc.1`. Leave the release note empty; the automation will fill it in from the checked in release note.
- [x] Release any docs updates by creating a `v[semver]` tag.
      **Note**: Docs should be released only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml).
- [x] Trigger algolia search crawler [workflow](https://github.com/spiceai/docs/actions/workflows/trigger_search_reindex.yml), to reindex updated docs.
- [x] Update the [Helm chart](https://github.com/spiceai/spiceai/blob/trunk/deploy/chart) version (image.tag version & chart version). Ensure [docker build](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml) for the tag from the release branch completed (~2 hours) and trigger the [Release Chart](https://github.com/spiceai/helm-charts/actions/workflows/release.yml) workflow.
      **Note**: Release chart workflow should be triggered only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml) and [docker image have finished building](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml).
- [x] Set the [release](https://github.com/spiceai/spiceai/releases) as latest release after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml) and [docker image have finished building](https://github.com/spiceai/spiceai/actions/workflows/spiced_docker.yml)
- [x] Final test pass on released binaries
- [x] Run [Generate Spicepod JSON schema](https://github.com/spiceai/spiceai/actions/workflows/generate_json_schema.yml)
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
- [x] Update `version.txt` and version in `Cargo.toml` to the next scheduled release version.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai).
      **Note**: Ensure that the Homebrew taps are updated only after the [binaries have finished building](https://github.com/spiceai/spiceai/actions/workflows/build_and_release.yml).
- [x] Remove the released version from the [ROADMAP](https://github.com/spiceai/spiceai/blob/trunk/docs/ROADMAP.md)
- [x] Update supported version in SECURITY.md

## Announcement Checklist

- [x] X: [@spice_ai](https://twitter.com/spice_ai)
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai)
- [x] Discord: [#announcements](https://discord.gg/zv8ahzZVpf)
- [x] Telegram: [spiceai](https://t.me/spiceai)
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org)
