### ISSUE TITLE
v0.9.1-alpha endgame

### ISSUE THREAD

**Issue by digadeesh** [spiceai/spiceai#824]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @y-f-u  |
| QA      | @mitchdevenport   |
| Docs    | @digadeesh  |

## Milestone Release Timeline

| Date         | Description |
| ------------ | ----------- |
| Planning     | TBD |
| Release      | TBD|
| Announcement | TBD |

## Checklist

- [x] All outstanding `spiceai` feature PRs are merged @phillipleblanc 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @y-f-u 
   - [x] one more small fix PR on the readme is coming in @Jeadie 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @ewgenius 
- [ ] ~~Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!)~~
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @Jeadie 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @ewgenius 
- [x] Merge Registry PRs
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @digadeesh 
- [x] ~~Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls)~~ @digadeesh 
- [x] Update release notes @y-f-u 
- [x] Update acknowledgements @Jeadie 
- [x] Verify `version.txt` and version in `Cargo.toml` is correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update)
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch
- [x] QA DRI sign-off
- [x] Docs DRI sign-off
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it.
- [x] Release the new version by creating a draft release with the tag from the release branch.
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai)
- [x] Release any docs updates by creating a `v[semver]` tag.
- [x] Final test pass on released binaries
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml)
   https://github.com/spiceai/spiceai/actions/runs/8428899155 ✅
- [x] [Reddit announcement](https://www.reddit.com/r/spiceai/comments/1bnwwxn/spice_v091_is_now_available/) to [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @phillipleblanc or @lukekim ✅
- [ ] ~~Discord announcement to [#announcements](https://discord.gg/zv8ahzZVpf)~~
- [x] Blog publish @digadeesh 
- [ ] ~~For major releases, [blog.spiceai.org](https://blog.spiceai.org) announcement~~
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version.
## PR reference

- PR 1.
- PR 2.
- etc.
