### ISSUE TITLE
v0.10-alpha endgame

### ISSUE THREAD

**Issue by phillipleblanc** [spiceai/spiceai#961]
## DRIs

|         | DRI               |
| ------- | ----------------- |
| Endgame | @phillipleblanc  |
| QA      | @ewgenius   |
| Docs    | @digadeesh  |
| Comms   | @lukekim  |

## Milestone Release Timeline

| Date         | Description            |
| ------------ | ---------------------- |
| Planning     | Mon, Mar 25 |
| Release      | Wed, Mar 27 |
| Announcement | Thu, Mar 28 |

## Planning Checklist

- [x] Review the specific [GitHub Milestone](https://github.com/spiceai/spiceai/milestones)

## Release Checklist

- [x] All outstanding `spiceai` feature PRs are merged @phillipleblanc 
- [x] Full test pass and update if necessary over README.md (please get screenshots!) @digadeesh 
- [x] Full test pass and update if necessary over Docs (please get screenshots!) @digadeesh 
- [x] Full test pass and update if necessary over existing and new Samples (please get screenshots/videos!) @ewgenius 
  - [x] Test acceleration sample @Jeadie 
  - [x] Test sales-bi sample @y-f-u 
- [x] Full test pass and update if necessary over existing and new Quickstarts (please get screenshots/videos!) @ewgenius 
  - [x] Review/test Apache Superset quickstart @mitchdevenport 
  - [x] Review/test Databricks quickstart @mitchdevenport 
  - [x] Review/test PostgreSQL quickstart @phillipleblanc 
  - [x] Review/test AWS RDS quickstart @ewgenius 
  - [x] Review/test Supabase quickstart @Jeadie 
  - [x] Review/test Dremio quickstart @Jeadie 
  - [x] Review/test Spice.ai Cloud Platform quickstart @mitchdevenport 
  - [x] Review/test S3 quickstart @phillipleblanc 
- [x] Merge [Docs PRs](https://github.com/spiceai/docs/pulls) @phillipleblanc 
  - [x] Update Docs banner to indicate the new released version
- [x] Merge Registry PRs @phillipleblanc 
- [x] Merge [Samples PRs](https://github.com/spiceai/samples/pulls) @phillipleblanc 
- [x] Merge [Quickstarts PRs](https://github.com/spiceai/samples/pulls) @phillipleblanc 
- [x] Update release notes @lukekim 
- [x] Update acknowledgements by triggering [Generate Acknowledgements](https://github.com/spiceai/spiceai/actions/workflows/generate_acknowledgements.yml) workflow @ewgenius 
- [x] Verify `version.txt` and version in `Cargo.toml` is correct using [docs/RELEASE.md](https://github.com/spiceai/spiceai/blob/trunk/docs/RELEASE.md#version-update) @phillipleblanc 
- [x] Ensure [E2E Test CI](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_ci.yml) is green on trunk branch @ewgenius 
- [x] QA DRI sign-off @ewgenius 
- [x] Docs DRI sign-off @digadeesh 
- [x] Create a new branch `release-v[semver]` and merge all relevant changes into it. E.g. `release-v0.9.1-alpha` @phillipleblanc 
- [x] Release the new version by creating a `pre-release` [GitHub Release](https://github.com/spiceai/spiceai/releases/new) with the tag from the release branch. E.g. `v0.9.1-alpha` @phillipleblanc 
- [x] Release any docs updates by creating a `v[semver]` tag. @phillipleblanc 
- [x] Final test pass on released binaries @phillipleblanc 
- [x] Run [E2E Test Release Installation](https://github.com/spiceai/spiceai/actions/workflows/e2e_test_release_install.yml) @ewgenius 
- [x] Update `version.txt` and version in `Cargo.toml` to the next release version. @phillipleblanc 
- [x] Update versions in [brew taps](https://github.com/spiceai/homebrew-spiceai) @phillipleblanc 
- [x] Remove the released version from the [ROADMAP](docs/ROADMAP.md) @phillipleblanc 

## Announcement Checklist

- [x] ~~X: [@spice_ai](https://twitter.com/spice_ai)~~
- [x] Reddit: [reddit.com/r/spiceai](https://reddit.com/r/spiceai) @lukekim 
- [x] ~~Discord: [#announcements](https://discord.gg/zv8ahzZVpf)~~
- [x] ~~Telegram: [spiceai](https://t.me/spiceai)~~
- [x] Blog: [blog.spiceai.org](https://blog.spiceai.org) @y-f-u 

## PR reference

- PR 1.
- PR 2.
- etc.

**Comment by phillipleblanc** [comment]
Released!
